# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTest445588():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test445588(self):
        self.open_home_page()
        self.driver.set_window_size(1550, 838)
        self.login()
        self.init_group_page()
        self.create_group()
        self.return_to_group_page()
        self.logout()

    def logout(self):
        self.driver.find_element(By.LINK_TEXT, "Logout").click()

    def return_to_group_page(self):
        self.driver.find_element(By.LINK_TEXT, "group page").click()

    def create_group(self):
        # fill group form
        self.driver.find_element(By.NAME, "group_name").click()
        self.driver.find_element(By.NAME, "group_name").send_keys("vvvvvvvvvvvvv")
        self.driver.find_element(By.NAME, "group_header").click()
        self.driver.find_element(By.NAME, "group_header").send_keys("vvvvvvvvvvvvvvvvv")
        self.driver.find_element(By.NAME, "group_footer").click()
        self.driver.find_element(By.NAME, "group_footer").send_keys("vvvvvvvvvvvvvvvvvvvv")
        # submit group creation
        self.driver.find_element(By.NAME, "submit").click()

    def init_group_page(self):
        self.driver.find_element(By.NAME, "new").click()

    def login(self):
        self.driver.find_element(By.NAME, "user").click()
        self.driver.find_element(By.NAME, "user").send_keys("admin")
        self.driver.find_element(By.NAME, "pass").click()
        self.driver.find_element(By.NAME, "pass").send_keys("secret")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

    def open_home_page(self):
        self.driver.get("http://localhost/addressbook/group.php")
