# Generated by Selenium IDE

from model_for_group.group import Group
from fixture_for_group.application import Application
import pytest

@pytest.fixture
def app(request):
    # Создание фикстуры
    fixture = Application()
    # Указание на то,как фикстура должна быть разрушена
    request.addfinalizer(fixture.destroy)
    return fixture

def test_add_groups_new(app):
    app.login(username="admin", password="secret")
    app.create_group(Group(name="Тест по уроку 14 - вынос переменных в класс", header = "test_one", footer="test_two"))
    app.logout()

def test_add_groups_new_pustaya(app):
    app.login(username="admin", password="secret")
    app.create_group(Group(name="", header="", footer=""))
    app.logout()

