# Generated by Selenium IDE


from model_for_group.group import Group


def test_add_groups_new(app):
    app.group.create(Group(name="Тест по уроку 14 - вынос переменных в класс", header="test_one", footer="test_two"))


def test_add_groups_new_pustaya(app):
    app.group.create(Group(name="", header="", footer=""))
